### ISSUE TITLE
双引号的问题

### ISSUE THREAD

**Issue by hellodword** [hedzr/cmdr#3]
```go

const (
	versionName = "0.0.1"
	appName     = "cmdrtest"
)

func buildRootCmd() (rootCmd *cmdr.RootCommand) {

	root := cmdr.Root(appName, versionName)

	root.NewFlag(cmdr.OptFlagTypeString).
		Titles("o", "output-file").
		Description("output file", "").
		DefaultValue("", "").
		OnSet(func(keyPath string, value interface{}) {
			fmt.Println(keyPath)
			os.Exit(0)
			return
		})

	rootCmd = root.RootCommand()

	return
}

func main() {

	rootCmd := buildRootCmd()
	if err := cmdr.Exec(rootCmd,
		cmdr.WithBuiltinCommands(false, false, false, false, false),
	); err != nil {
		panic(err)
	}
}
```

编译完如果 `cmdrtest -o ""` 就会 panic

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hedzr/cmdr.(*ptpkg).preprocessPkg(0xc0002c6000, 0xc00002a0c0, 0x3, 0x4, 0x0, 0x5)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/ptpkg.go:170 +0x33a
github.com/hedzr/cmdr.(*ptpkg).processTypeString(0xc0002c6000, 0xc00002a0c0, 0x3, 0x4, 0xffffffffffffffff, 0xc0000220d1)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/ptpkg.go:280 +0x6e
github.com/hedzr/cmdr.(*ptpkg).tryExtractingValue(0xc0002c6000, 0xc00002a0c0, 0x3, 0x4, 0xc0002784e8, 0x9e509f)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/ptpkg.go:100 +0x112
github.com/hedzr/cmdr.(*ExecWorker).flagsMatched(0xc0002b8120, 0xc0002c6000, 0xc0002981c0, 0xc00002a0c0, 0x3, 0x4, 0x9c8ede, 0xc0002c6000, 0xc0002c6028)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/exec_match.go:133 +0x5f
github.com/hedzr/cmdr.(*ExecWorker).flagsMatching(0xc0002b8120, 0xc0002c6000, 0xc0002981c0, 0xc00022be48, 0xc00002a0c0, 0x3, 0x4, 0x0, 0x0, 0x0)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/exec_match.go:99 +0x3ce
github.com/hedzr/cmdr.(*ExecWorker).xxTestCmd(0xc0002b8120, 0xc0002c6000, 0xc00022be48, 0xc0002981c0, 0xc00002a0c0, 0x3, 0x4, 0x0, 0x1, 0xc000134060)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/exec.go:244 +0x15c
github.com/hedzr/cmdr.(*ExecWorker).InternalExecFor(0xc0002b8120, 0xc0002981c0, 0xc00002a0c0, 0x3, 0x4, 0x0, 0x0)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/exec.go:194 +0x2da
github.com/hedzr/cmdr.Exec(0xc0002981c0, 0xc00022bf38, 0x1, 0x1, 0x43e6c1, 0x1081ec0)
        $GOPATH/pkg/mod/github.com/hedzr/cmdr@v1.6.7/exec.go:88 +0x9e
main.main()

```

单引号的话就没问题~

**Comment by hedzr** [comment]
确实够深。
在那里，我就是懒了下，不想写个很长的if，而且有点烧脑，没想到总是会有人挑战到。

由于golang版本发布缘故，下个版本发布时会彻底解决问题。当前只要不提供临界参数，还是ok的。

稍后进一步说话

**Comment by hedzr** [comment]
另外，代码中有一些问题：

1. 对于接受string的flag，你要指定 String 而不是 bool
   ```go
	root.NewFlag(cmdr.OptFlagTypeString).
		Titles("o", "output-file").
		Description("output file", "").
		DefaultValue("", "").
		OnSet(func(keyPath string, value interface{}) {
			fmt.Println(keyPath, value)
			os.Exit(0)
			return
		})
   ```

2. 对于一个flag，你应该使用 Action 而不是 OnSet，尽管可能能达到相似的效果。
   不过这个问题太深入了，暂时不讲了，可以看代码

3. 对于这个例子，你想要的可能更应该是在 root 中增加 Action，然后实现你的处理逻辑：

   ```go
	root := cmdr.Root(appName, versionName).
		// PreAction, PostAction
		Action(func(cmd *cmdr.Command, args []string) (err error) {
			filename := cmdr.GetStringR("output-file")
			fmt.Println(filename)
			return
		})
   ```

GetStringR 等等 GetXXXR是最建议的提取flag值的方法，根据命令嵌套的层级，可以通过 `cmd1.cmd2.flag1` 的方式拿到flag值；
在每个命令的 Action 中实现对应的逻辑，而不是通过 OnSet。OnXXX通常是就地的，但命令的 Action  会在命令行完整处理之后才会被触发，那里才是正确的放业务逻辑的地方。

**Comment by hedzr** [comment]
虽然尚未发布 v1.6.9，但是还是有必要提示一下，届时使用下面的方法定义 flag 才是被建议的：

```go
	root.NewFlagV("/var/lib/a").
		Titles("o", "output-file").
		Description("output file", "").
		Placeholder("PATH")
```

**Comment by hellodword** [comment]
感谢耐心解答~
